tool_gun_stock_portfolio_instrument:
    resource: "@ToolGunStockPortfolioBundle/Resources/config/routing/instrument.yml"
    prefix:   /instrument

tool_gun_stock_portfolio_position:
    resource: "@ToolGunStockPortfolioBundle/Resources/config/routing/position.yml"
    prefix:   /position

tool_gun_stock_portfolio_transaction:
    resource: "@ToolGunStockPortfolioBundle/Resources/config/routing/transaction.yml"
    prefix:   /transaction

tool_gun_stock_portfolio_homepage:
    path:     /
    defaults: { _controller: ToolGunStockPortfolioBundle:Home:index }


tool_gun_stock_portfolio_valuation:
    path:     /valuation/{method}
    defaults: { _controller: ToolGunStockPortfolioBundle:Home:valuation, method: fifo }
