instrument_index:
    path:     /
    defaults: { _controller: "ToolGunStockPortfolioBundle:Instrument:index" }
    methods:  GET

instrument_show:
    path:     /{id}/show
    defaults: { _controller: "ToolGunStockPortfolioBundle:Instrument:show" }
    methods:  GET

instrument_new:
    path:     /new
    defaults: { _controller: "ToolGunStockPortfolioBundle:Instrument:new" }
    methods:  [GET, POST]

instrument_edit:
    path:     /{id}/edit
    defaults: { _controller: "ToolGunStockPortfolioBundle:Instrument:edit" }
    methods:  [GET, POST]

instrument_delete:
    path:     /{id}/delete
    defaults: { _controller: "ToolGunStockPortfolioBundle:Instrument:delete" }
    methods:  DELETE
