transaction_index:
    path:     /
    defaults: { _controller: "ToolGunStockPortfolioBundle:Transaction:index" }
    methods:  GET

transaction_show:
    path:     /{id}/show
    defaults: { _controller: "ToolGunStockPortfolioBundle:Transaction:show" }
    methods:  GET

transaction_new:
    path:     /new
    defaults: { _controller: "ToolGunStockPortfolioBundle:Transaction:new" }
    methods:  [GET, POST]

transaction_edit:
    path:     /{id}/edit
    defaults: { _controller: "ToolGunStockPortfolioBundle:Transaction:edit" }
    methods:  [GET, POST]

transaction_delete:
    path:     /{id}/delete
    defaults: { _controller: "ToolGunStockPortfolioBundle:Transaction:delete" }
    methods:  DELETE
